<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>CyberDefenderIconColoredt.png_no_bg.png</PackageIcon>
    <ApplicationIcon>Assets\CyberDefenderIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\13.png" />
    <None Remove="Assets\AccountDeletion.png" />
    <None Remove="Assets\AccountLockout.png" />
    <None Remove="Assets\AdBlocker.png" />
    <None Remove="Assets\AltF4Close.png" />
    <None Remove="Assets\AnimatedBanner.gif" />
    <None Remove="Assets\APIExploitation.png" />
    <None Remove="Assets\Baiting.png" />
    <None Remove="Assets\Banner.png_no_bg.png" />
    <None Remove="Assets\Bluesnarfing.png" />
    <None Remove="Assets\BluetoothVisibilityOFF.png" />
    <None Remove="Assets\BookmarkManager.png" />
    <None Remove="Assets\BoottimeScanner.png" />
    <None Remove="Assets\Botnet.png" />
    <None Remove="Assets\BotnetColored.png" />
    <None Remove="Assets\BrowserSandbox.png" />
    <None Remove="Assets\BruteForce.png" />
    <None Remove="Assets\BruteForceColored.png" />
    <None Remove="Assets\ButtonBG.png" />
    <None Remove="Assets\cancel.wav" />
    <None Remove="Assets\Card.wav" />
    <None Remove="Assets\CardScreen.png" />
    <None Remove="Assets\CICCPNPReport.png" />
    <None Remove="Assets\Clickjacking.png" />
    <None Remove="Assets\CodeReviewer.png" />
    <None Remove="Assets\ContentSecurityPolicy.png" />
    <None Remove="Assets\Correct.wav" />
    <None Remove="Assets\CredentialSurfing.png" />
    <None Remove="Assets\CredentialSurfingColored.png" />
    <None Remove="Assets\CryptoJacking.png" />
    <None Remove="Assets\CyberDefenderIcon.ico" />
    <None Remove="Assets\CyberDefenderIconColored.ico" />
    <None Remove="Assets\CyberLibel.png" />
    <None Remove="Assets\CyberLibelColored.png" />
    <None Remove="Assets\cyberpunk-street.wav" />
    <None Remove="Assets\CyberSentinel.png" />
    <None Remove="Assets\CyDAssistant.png" />
    <None Remove="Assets\DataBreach.png" />
    <None Remove="Assets\DataBreachColored.png" />
    <None Remove="Assets\DataFreelancer.png" />
    <None Remove="Assets\DataPrivacyAudit.png" />
    <None Remove="Assets\DDoSAttack.png" />
    <None Remove="Assets\DDoSAttackColored.png" />
    <None Remove="Assets\DDoSMitigationCDN.png" />
    <None Remove="Assets\DeepfakeScam.png" />
    <None Remove="Assets\DefaultPasswordReset.png" />
    <None Remove="Assets\DefenseCardbg.png" />
    <None Remove="Assets\DigitalEvidenceLog.png" />
    <None Remove="Assets\DocumentShredder.png" />
    <None Remove="Assets\DriveByDownload.png" />
    <None Remove="Assets\DumpsterDiving.png" />
    <None Remove="Assets\EmailHeaderInspector.png" />
    <None Remove="Assets\EstablishFamilyCode.png" />
    <None Remove="Assets\EvilTwin.png" />
    <None Remove="Assets\EvilTwinColored.png" />
    <None Remove="Assets\female.png" />
    <None Remove="Assets\FilelessMalware.png" />
    <None Remove="Assets\FirmwarePatch.png" />
    <None Remove="Assets\FormJacking.png" />
    <None Remove="Assets\FrameBusterScript.png" />
    <None Remove="Assets\GamePlayScreen.png" />
    <None Remove="Assets\Gemini_Generated_Image_v7nmqcv7nmqcv7nm-removebg-preview.png" />
    <None Remove="Assets\GrandArchitect.png" />
    <None Remove="Assets\HoneyToken.png" />
    <None Remove="Assets\HTTPSSSLCertificate.png" />
    <None Remove="Assets\IdentityTheft.png" />
    <None Remove="Assets\IdentityTheftColored.png" />
    <None Remove="Assets\ImmutableColdBackup.png" />
    <None Remove="Assets\Incorrect.wav" />
    <None Remove="Assets\InputSanitizer.png" />
    <None Remove="Assets\InsiderThreat.png" />
    <None Remove="Assets\IoTHacking.png" />
    <None Remove="Assets\JuiceJackingColoredpng.png" />
    <None Remove="Assets\JuiceJackingpng.png" />
    <None Remove="Assets\KeyLogger.png" />
    <None Remove="Assets\KeyLoggerColored.png" />
    <None Remove="Assets\Level_One_Dawn.wav" />
    <None Remove="Assets\LogicBomb.png" />
    <None Remove="Assets\LoginScreenBg.png" />
    <None Remove="Assets\lose.wav" />
    <None Remove="Assets\MainMenuGifTest.gif" />
    <None Remove="Assets\MainMenuScreen1.png" />
    <None Remove="Assets\male.png" />
    <None Remove="Assets\MaliciousLink.png" />
    <None Remove="Assets\MaliciousLinkColored.png" />
    <None Remove="Assets\Malvertising.png" />
    <None Remove="Assets\Malware_Virus.png" />
    <None Remove="Assets\Malware_VirusColored.png" />
    <None Remove="Assets\ManInTheMiddle.png" />
    <None Remove="Assets\ManInTheMiddleColored.png" />
    <None Remove="Assets\Netrunner.png" />
    <None Remove="Assets\NetworkSegmenter.png" />
    <None Remove="Assets\OAuth.png" />
    <None Remove="Assets\OfficialAppVerify.png" />
    <None Remove="Assets\PacketSniffing.png" />
    <None Remove="Assets\PasswordManager.png" />
    <None Remove="Assets\Pharming.png" />
    <None Remove="Assets\Phishing_Smishing.png" />
    <None Remove="Assets\Phishing_SmishingColored.png" />
    <None Remove="Assets\pop_1.wav" />
    <None Remove="Assets\PowershellMonitor.png" />
    <None Remove="Assets\PreparedStatements.png" />
    <None Remove="Assets\Pretexting.png" />
    <None Remove="Assets\PretextingColored.png" />
    <None Remove="Assets\PrincipleOfLeastPrivilege.png" />
    <None Remove="Assets\PrivacyScreenFilter.png" />
    <None Remove="Assets\ProfileScreen.png" />
    <None Remove="Assets\Ransomware.png" />
    <None Remove="Assets\RansomwareColored.png" />
    <None Remove="Assets\ResultScreen.jpg" />
    <None Remove="Assets\ResultScreen.png" />
    <None Remove="Assets\Rootkit.png" />
    <None Remove="Assets\SalamiAttack.png" />
    <None Remove="Assets\Scareware.png" />
    <None Remove="Assets\ScriptKiddie.png" />
    <None Remove="Assets\SearchEnginePoisoning.png" />
    <None Remove="Assets\SecureDNS.png" />
    <None Remove="Assets\select_1.wav" />
    <None Remove="Assets\ShoulderSurfing.png" />
    <None Remove="Assets\ShoulderSurfingColored.png" />
    <None Remove="Assets\SIMCarrierLock.png" />
    <None Remove="Assets\SIMSwapping.png" />
    <None Remove="Assets\Smishing.png" />
    <None Remove="Assets\SmishingColored.png" />
    <None Remove="Assets\SocialAwareness.png" />
    <None Remove="Assets\SocialEngineering.png" />
    <None Remove="Assets\SplashScreen1.png" />
    <None Remove="Assets\SplashScreen2.png" />
    <None Remove="Assets\SQLInjection.png" />
    <None Remove="Assets\SQLInjectionColored.png" />
    <None Remove="Assets\SystemDrifter.png" />
    <None Remove="Assets\TailgateAlarm.png" />
    <None Remove="Assets\Tailgating.png" />
    <None Remove="Assets\ThreatCardbg.png" />
    <None Remove="Assets\ThreatIntelligence.png" />
    <None Remove="Assets\TrojanHorse.png" />
    <None Remove="Assets\TwoFactorAuth.png" />
    <None Remove="Assets\TypoSquatting.png" />
    <None Remove="Assets\TypoSquattingColored.png" />
    <None Remove="Assets\USBDataBlocker.png" />
    <None Remove="Assets\VirtualMachine.png" />
    <None Remove="Assets\Vishing.png" />
    <None Remove="Assets\VPNTunnel.png" />
    <None Remove="Assets\WateringHole.png" />
    <None Remove="Assets\Whaling.png" />
    <None Remove="Assets\win.wav" />
    <None Remove="Assets\Worm.png" />
    <None Remove="Assets\XSS.png" />
    <None Remove="Assets\ZombieAccount.png" />
    <None Remove="EditProfileScreen.resx~RFc03bea.TMP" />
    <None Remove="ReviewsScreen.resx~RF24f4e73.TMP" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\AccountDeletion.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\AccountLockout.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\AdBlocker.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\AltF4Close.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\AnimatedBanner.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\APIExploitation.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Baiting.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Banner.png_no_bg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Bluesnarfing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\BluetoothVisibilityOFF.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\BookmarkManager.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\BoottimeScanner.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Botnet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\BrowserSandbox.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\BruteForce.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ButtonBG.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\cancel.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Card.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\CyberDefenderIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\CardScreen.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CICCPNPReport.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Clickjacking.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CodeReviewer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ContentSecurityPolicy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\Correct.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\CredentialSurfing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CryptoJacking.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CyberDefenderIcon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CyberDefenderIconColored.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CyberDefenderIconColoredt.png_no_bg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CyberLibel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\cyberpunk-street.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\CyberSentinel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\CyDAssistant.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DataBreach.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DataFreelancer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DataPrivacyAudit.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DDoSAttack.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DDoSMitigationCDN.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DeepfakeScam.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DefaultPasswordReset.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DefenseCardbg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DigitalEvidenceLog.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DocumentShredder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DriveByDownload.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\DumpsterDiving.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\EmailHeaderInspector.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\EstablishFamilyCode.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\EvilTwin.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\female.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\FilelessMalware.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\FirmwarePatch.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\FormJacking.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\FrameBusterScript.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\GamePlayScreen.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Gemini_Generated_Image_v7nmqcv7nmqcv7nm-removebg-preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\GrandArchitect.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\HoneyToken.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\HTTPSSSLCertificate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\IdentityTheft.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ImmutableColdBackup.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\Incorrect.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\InputSanitizer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\InsiderThreat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\IoTHacking.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\JuiceJackingpng.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\KeyLogger.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\Level_One_Dawn.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\LogicBomb.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\LoginScreenBg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\lose.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\MainMenuGifTest.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\MainMenuScreen1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\male.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\MaliciousLink.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Malvertising.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ManInTheMiddle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Netrunner.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\NetworkSegmenter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\OAuth.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\OfficialAppVerify.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\PacketSniffing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\PasswordManager.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Pharming.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Phishing_Smishing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\pop_1.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\PowershellMonitor.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\PreparedStatements.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Pretexting.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\PrincipleOfLeastPrivilege.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\PrivacyScreenFilter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ProfileScreen.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Ransomware.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ResultScreen.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Rootkit.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SalamiAttack.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Scareware.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ScriptKiddie.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SearchEnginePoisoning.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SecureDNS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\select_1.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\ShoulderSurfing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SIMCarrierLock.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SIMSwapping.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Smishing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SocialAwareness.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SocialEngineering.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SplashScreen1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SplashScreen2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SQLInjection.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\SystemDrifter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\TailgateAlarm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Tailgating.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ThreatCardbg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ThreatIntelligence.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\TrojanHorse.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\TwoFactorAuth.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\TypoSquatting.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\USBDataBlocker.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\VirtualMachine.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Vishing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\VPNTunnel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\WateringHole.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\Whaling.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Assets\win.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\Worm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\XSS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Assets\ZombieAccount.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Krypton.Toolkit" Version="105.26.4.110" />
    <PackageReference Include="ReaLTaiizor" Version="3.8.1.8" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.7" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\CyberDefenderIconColoredt.png_no_bg.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Assets\PixelifySans-Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\PixelifySans-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T14.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T15.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T16.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T17.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T18.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T19.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T20.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T21.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\T9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>